volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:

  foodgram_db:
    image: postgres:13.13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: kseniaaa/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - foodgram_db
    restart: always

  frontend:
    image: kseniaaa/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static_django/
      - media:/media/
      - static_frontend:/static_frontend/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

    depends_on:
      - backend
    restart: always