# Generated by Django 3.2.16 on 2024-01-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240108_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribed',
        ),
    ]
