# Generated by Django 3.2.16 on 2024-01-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_book_holder_library_librarybook_shoppinglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
