# Generated by Django 3.2.16 on 2024-01-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_shoppinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='librarybook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='librarybook',
            name='library',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Holder',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='LibraryBook',
        ),
    ]
