# Generated by Django 3.2.16 on 2024-01-07 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0030_tagrecipe'),
        ('lists', '0007_delete_shoppinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_in_shoppinglist', to='foodgram.recipe', verbose_name='Рецепт в корзине')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shoppingcart', to=settings.AUTH_USER_MODEL, verbose_name='Вы')),
            ],
            options={
                'verbose_name_plural': 'Список покупок',
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
