# Generated by Django 3.2.16 on 2023-12-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес тега')),
            ],
        ),
    ]
