# Generated by Django 3.2.16 on 2023-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_ingredientrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(help_text='Ингредиенты для приготовления блюда', related_name='recipes', through='foodgram.IngredientRecipe', to='foodgram.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
