# Generated by Django 3.2.16 on 2023-12-25 10:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_auto_20231225_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Цветовой HEX-код', image_field=None, max_length=25, samples=None, verbose_name='Цветовой HEX-код'),
        ),
    ]
