# Generated by Django 3.2.16 on 2023-12-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0008_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
