# Generated by Django 3.2.16 on 2023-12-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0012_auto_20231226_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
