# Generated by Django 3.2.16 on 2023-12-26 08:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0013_delete_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Favorite',
        ),
    ]
