# Generated by Django 3.2.16 on 2023-12-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0015_auto_20231226_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time',
            new_name='cookimg_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
