# Generated by Django 3.2.16 on 2023-12-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0017_auto_20231226_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cookimg_time',
            new_name='cooking_time',
        ),
    ]
