# Generated by Django 3.2.16 on 2023-12-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0019_auto_20231226_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='author',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
