# Generated by Django 3.2.16 on 2023-12-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0021_auto_20231226_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
