# Generated by Django 3.2.16 on 2023-12-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0023_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
