# Generated by Django 3.2.16 on 2023-12-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0025_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Тег, к которому будет относиться рецепт', related_name='recipe', to='foodgram.Tag', verbose_name='Тег'),
        ),
    ]
