# Generated by Django 3.2.16 on 2023-12-27 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0027_auto_20231227_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество ингредиентов'),
        ),
    ]
