# Generated by Django 3.2.16 on 2024-01-04 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0029_auto_20231227_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_in_recipe', to='foodgram.tag', verbose_name='Тег')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='foodgram.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name_plural': 'Теги/Рецепты',
            },
        ),
    ]
