# Generated by Django 3.2.16 on 2024-01-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0032_alter_ingredientrecipe_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagrecipe',
            old_name='ingredient',
            new_name='tag',
        ),
    ]
