name: Main Foodgram Workflow

on:
  push:
    branches:
      - master

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.11
        env:
          # POSTGRES_USER: foodgram_user
          # POSTGRES_PASSWORD: njeocwHOkb
          # POSTGRES_DB: foodgram_db
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8==6.0.0 flake8-isort==6.0.0
        pip install -r ./backend/foodgram_project/requirements.txt

    - name: Test with flake8
      run: python -m flake8 backend/
